In [1]:
import numpy as np

In [34]:
R = np.random.randint(-8, 8, 8)
I = np.random.randint(-8, 8, 8)
R, I

(array([ 3, -4,  1,  2,  3,  4, -7, -8]),
 array([ 5,  7,  2,  5,  0,  5, -4, -2]))

In [35]:
I[I < 0] += 16
Q = R * 16 + I
Q

array([  53,  -57,   18,   37,   48,   69, -100, -114])

In [36]:
R = Q // 16
R

array([ 3, -4,  1,  2,  3,  4, -7, -8])

In [37]:
I = Q - 16 * R
I[I >= 8] -= 16
I

array([ 5,  7,  2,  5,  0,  5, -4, -2])